// Auto-generated by ConvertToImposter.cs
// Instructs the Imposter source generator to create imposters for each type.
// See: https://themidnightgospel.github.io/Imposter/latest/
//
// After a build, use the generated imposters in tests:
//   C# 14:   var imposter = IMyService.Imposter();
//   C#  9+:  var imposter = new IMyServiceImposter();
//
// ⚠  IMPORTANT: API difference vs NSubstitute
//   NSubstitute: mock IS the interface (mock.Method() both sets up AND acts)
//   Imposter:    imposter.Method().Returns(…) → setup / verify
//                imposter.Instance().Method() → act (pass to SUT)
//
// So wherever the old mock was passed to a constructor or method,
// use mockInstance (the .Instance() value) instead.

using CloudBurger.Tests.Services;
using Imposter.Abstractions;

[assembly: GenerateImposter(typeof(ITestService))]
[assembly: GenerateImposter(typeof(Microsoft.Extensions.Logging.ILogger))]
